version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - n8n_net

  n8n:
    image: n8nio/n8n:1.106.3
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - DB_TYPE=mongodb
      - DB_MONGODB_CONNECTION_URL=mongodb://mongodb:27017/n8n
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - mongodb
    networks:
      - n8n_net

volumes:
  mongo_data:
  n8n_data:

networks:
  n8n_net:
    driver: bridge